#!/bin/bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my twitter page.

# Step 1: Install Nginx web server
sudo apt update
sudo apt install nginx -y

# Step 2: Configure the redirection
sudo rm /etc/nginx/sites-enabled/default
sudo touch /etc/nginx/sites-available/redirect_me
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Step 3: Edit the redirection configuration
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name _;
    return 301 https://twitter.com/joeotine;
}
EOF'

# Step 4: Restart Nginx to apply the changes
sudo systemctl restart nginx
