#!/usr/bin/env bash
# This script will genereate a MySQL dump and create a compressed archive  of it

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
